# Default values for multi-region-app chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/google-samples/hello-app
  tag: "1.0"
  pullPolicy: IfNotPresent

# -- Set to true for the cluster that should manage the MultiClusterIngress and MultiClusterService
isConfigCluster: false

service:
  type: ClusterIP
  port: 8080

pdb:
  enabled: true
  minAvailable: 1