apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multi_region_app.fullname" . }}
  labels:
    {{- include "multi_region_app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "multi_region_app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "multi_region_app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "128Mi"
            {{- toYaml .Values.resources | nindent 12 }}
