# Default values for simple-app chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/google-samples/hello-app
  tag: "1.0"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

service:
  type: ClusterIP
  port: 80

pdb:
  enabled: true
  minAvailable: 1
